import QtQuick 2.15

QtObject {
    //主题色
    property color themeOneColor: "#97B9FF"
    //辅助色1
    property color auxiliaryColor: "#205EFF"
    //主题色2 辅助色2
    property color themeTwoColor: "#E1FF01"
    //衍生主题色
    property color themeOneColor1: "#EBF2FF"
    property color themeOneColor2: "#D7E0F3"
    property color themeOneColor3: "#C4D0E8"
    property color themeOneColor4: "#AFBDDA"
    property color themeOneColor5: "#A0B1D4"
    property color themeOneColor6: "#8EAEF2"
    property color themeOneColor7: "#84A1E0"
    property color themeOneColor8: "#4A556E"
    property color themeOneColor9: "#343B4B"
    //功能色
    property color funcColor1: "#ED2020"
    property color funcColor2: "#F8A7A7"
    property color funcColor3: "#F6E1E1"
    property color funcColor4: "#FF9900"
    property color funcColor5: "#FFC369"
    property color funcColor6: "#E4D9B0"
    property color funcColor7: "#00D897"
    property color funcColor8: "#84EDCD"
    property color funcColor9: "#D0DFCD"
    //背景色
    property color backgroundColor: "#000000"
    //对应中性1-7
    property color color1: "#FFFFFF"
    property color color2: "#E8EAED"
    property color color3: "#C3C5C9"
    property color color4: "#999B9F"
    property color color5: "#3B3D41"
    property color color6: "#1E2024"
    property color color7: "#161719"

    property color textColor: "#FFFFFF"
    property url   imageSource: "dark-theme-image.png"

    //"主页"模块
    property string max_bettary:"qrc:/Image/Icon/ms_maxBettary_dark.png"

    // “灯光”模块
    property string lighting_add_normal: "qrc:/Image/Function/Lighting/add_normal_dark.svg"
    property string lighting_add_hover: "qrc:/Image/Function/Lighting/add_hover_dark.svg"
    property string dynamic_normal: "qrc:/Image/Function/Lighting/dynamic_normal_dark.svg"
    property string dynamic_checked: "qrc:/Image/Function/Lighting/dynamic_checked_dark.svg"
    property string static_normal: "qrc:/Image/Function/Lighting/static_normal_dark.svg"
    property string static_checked: "qrc:/Image/Function/Lighting/static_checked_dark.svg"
    property string up_and_down_gradient_normal: "qrc:/Image/Function/Lighting/up_and_down_gradient_normal_dark.svg"
    property string up_and_down_gradient_hover: "qrc:/Image/Function/Lighting/up_and_down_gradient_hover_dark.svg"
    property string up_and_down_gradient_pressed: "qrc:/Image/Function/Lighting/up_and_down_gradient_pressed_dark.svg"
    property string left_and_right_gradient_normal: "qrc:/Image/Function/Lighting/left_and_right_gradient_normal_dark.svg"
    property string left_and_right_gradient_hover: "qrc:/Image/Function/Lighting/left_and_right_gradient_hover_dark.svg"
    property string left_and_right_gradient_pressed: "qrc:/Image/Function/Lighting/left_and_right_gradient_pressed_dark.svg"

    // “性能”模块“宏定义”面板
    property string macro_edit_normal: "qrc:/Image/Function/Remap/edit_normal_dark.svg"
    property string macro_edit_hover: "qrc:/Image/Function/Remap/edit_hover_dark.svg"
    property string macro_edit_pressed: "qrc:/Image/Function/Remap/edit_pressed_dark.svg"
    property string macro_delete_normal: "qrc:/Image/Function/Remap/delete_normal_dark.svg"
    property string macro_delete_hover: "qrc:/Image/Function/Remap/delete_hover_dark.svg"
    property string macro_delete_pressed: "qrc:/Image/Function/Remap/delete_pressed_dark.svg"
    property string macro_download_normal: "qrc:/Image/Function/Remap/download_normal_dark.svg"
    property string macro_download_hover: "qrc:/Image/Function/Remap/download_hover_dark.svg"
    property string macro_download_pressed: "qrc:/Image/Function/Remap/download_pressed_dark.svg"
    property string macro_return: "qrc:/Image/Function/Remap/return_dark.svg"
    property string macro_import: "qrc:/Image/Function/Remap/import_dark.svg"
    property string macro_export: "qrc:/Image/Function/Remap/export_dark.svg"
    property string macro_rBtn_unchecked: "qrc:/Image/Icon/rBtn_unchecked_dark.svg"
    property string create_new_macro_btn_normal: "qrc:/Image/Function/Remap/create_new_macro_normal_dark.svg"
    property string create_new_macro_btn_hover: "qrc:/Image/Function/Remap/create_new_macro_hover.svg"
    property string create_new_macro_btn_pressed: "qrc:/Image/Function/Remap/create_new_macro_pressed.svg"
    property string start_recording_normal: "qrc:/Image/Function/Remap/start_recording_normal_dark.svg"
    property string start_recording_pressed: "qrc:/Image/Function/Remap/start_recording_pressed.svg"
    property string recorded_content_panel: "qrc:/Image/Function/Remap/recorded_content_panel_dark.svg"
    property string key_press: "qrc:/Image/Function/Remap/key_press_dark.svg"
    property string key_release: "qrc:/Image/Function/Remap/key_release_dark.svg"
    property string left_mouse_button: "qrc:/Image/Function/Remap/left_mouse_button_dark.svg"
    property string middle_mouse_button: "qrc:/Image/Function/Remap/middle_mouse_button_dark.svg"
    property string right_mouse_button: "qrc:/Image/Function/Remap/right_mouse_button_dark.svg"
    property string key_press_checked: "qrc:/Image/Function/Remap/key_press_day.svg"
    property string key_release_checked: "qrc:/Image/Function/Remap/key_release_day.svg"

    //"设置" 模块
    property string device_firmware_update:"qrc:/Image/Function/Version/device_firmware_update_icon_dark.svg"
    property string dongle_firmware_update:"qrc:/Image/Function/Version/dongle_firmware_update_icon_dark.svg"
    property string power_setting:"qrc:/Image/Function/Version/power_setting_icon_dark.svg"
    property string toggleBtn_off:"qrc:/Image/Function/Lighting/toggleBtn_off_dark.svg"
    property string power_setting_control:"qrc:/Image/Function/Version/power_setting_control_background_dark.svg"

    // 顶部栏
    property string setting_normal: "qrc:/Image/TitleView/setting_normal_dark.svg"
    property string setting_hover: "qrc:/Image/TitleView/setting_hover_dark.svg"
    property string setting_clicked: "qrc:/Image/TitleView/setting_clicked_dark.svg"
    property string homePage_normal: "qrc:/Image/TitleView/homePage_normal_dark.svg"
    property string homePage_hover: "qrc:/Image/TitleView/homePage_hover_dark.svg"
    property string homePage_clicked: "qrc:/Image/TitleView/homePage_clicked_dark.svg"
    property string profile_normal: "qrc:/Image/TitleView/profile_normal_dark.svg"
    property string profile_hover: "qrc:/Image/TitleView/profile_hover_dark.svg"
    property string profile_clicked: "qrc:/Image/TitleView/profile_clicked_dark.svg"
    property string moon_normal: "qrc:/Image/TitleView/moon_normal_dark.svg"
    property string moon_hover: "qrc:/Image/TitleView/moon_hover_dark.svg"
    property string moon_clicked: "qrc:/Image/TitleView/moon_clicked_dark.svg"
    property string light_normal: "qrc:/Image/TitleView/Light_normal_dark.svg"
    property string light_hover: "qrc:/Image/TitleView/Light_hover_dark.svg"
    property string light_clicked: "qrc:/Image/TitleView/Light_clicked_dark.svg"
    property string close_normal: "qrc:/Image/TitleView/close_normal_dark.svg"
    property string close_hover: "qrc:/Image/TitleView/close_hover_dark.svg"
    property string close_clicked: "qrc:/Image/TitleView/close_clicked_dark.svg"
    property string minus_normal: "qrc:/Image/TitleView/minus_normal_dark.svg"
    property string minus_hover: "qrc:/Image/TitleView/minus_hover_dark.svg"
    property string minus_clicked: "qrc:/Image/TitleView/minus_clicked_dark.svg"
    property string restore_normal: "qrc:/Image/TitleView/restore_normal_dark.svg"
    property string restore_hover: "qrc:/Image/TitleView/restore_hover_dark.svg"
    property string restore_clicked: "qrc:/Image/TitleView/restore_clicked_dark.svg"
    property string restore_stop: "qrc:/Image/TitleView/restore_stop_dark.svg"
    property string save_normal: "qrc:/Image/TitleView/save_normal_dark.svg"
    property string save_hover: "qrc:/Image/TitleView/save_hover_dark.svg"
    property string save_clicked: "qrc:/Image/TitleView/save_clicked_dark.svg"
    property string save_stop: "qrc:/Image/TitleView/save_stop_dark.svg"
    property string pre_step_normal: "qrc:/Image/TitleView/PreviousStep_normal_dark.svg"
    property string pre_step_hover: "qrc:/Image/TitleView/PreviousStep_hover_dark.svg"
    property string pre_step_clicked: "qrc:/Image/TitleView/PreviousStep_clicked_dark.svg"
    property string pre_step_stop: "qrc:/Image/TitleView/PreviousStep_stop_dark.svg"

    //设置页
    property string next_step_normal: "qrc:/Image/TitleView/NextStep_normal_dark.svg"
    property string next_step_hover: "qrc:/Image/TitleView/NextStep_hover_dark.svg"
    property string next_step_clicked: "qrc:/Image/TitleView/NextStep_clicked_dark.svg"
    property string next_step_stop: "qrc:/Image/TitleView/NextStep_stop_dark.svg"
    property string switch_normal: "qrc:/Image/TitleView/switch_normal_dark.svg"
    property string switch_hover: "qrc:/Image/TitleView/switch_hover_dark.svg"
    property string switch_clicked: "qrc:/Image/TitleView/switch_clicked_dark.svg"
    property string tip_other:"qrc:/Image/TitleView/tip_dark.png"
    property string password:"qrc:/Image/TitleView/password_dark.svg"
    property string pairStepOne:"qrc:/Image/TitleView/pairStepOne_dark.svg"
    property string pairStepTwo:"qrc:/Image/TitleView/pairStepTwo_dark.svg"
    property string pairStepThree:"qrc:/Image/TitleView/pairStepThree_dark.svg"
    property string pairStepFour:"qrc:/Image/TitleView/pairStepFour_dark.svg"
    property string nodelected:"qrc:/Image/TitleView/notDetected_day.svg"
    property string convertConfigure_normal:"qrc:/Image/TitleView/convertConfigure_normal_dark.svg"
    property string convertConfigure_hover:"qrc:/Image/TitleView/convertConfigure_hover_dark.svg"
    property string convertConfigure_clicked:"qrc:/Image/TitleView/convertConfigure_clicked_dark.svg"
    property string delete_configure:"qrc:/Image/TitleView/delete_dark.svg"
    property string copy_configure:"qrc:/Image/TitleView/copy_dark.svg"
    property string list_configure:"qrc:/Image/TitleView/list_dark.svg"
    property string addConfigureList:"qrc:/Image/TitleView/addConfigure_dark.svg"
    property string deleteConfigureList:"qrc:/Image/TitleView/deleteConfigure_dark.svg"
    property string editConfigureList:"qrc:/Image/TitleView/editConfigure_dark.svg"
    property string updateImage:"qrc:/Image/TitleView/update_dark.png"
}
